// src/views/Contact.vue
<template>
<text-page>
    <h2>Contact</h2>
    <p>Feel free to contact me if you would like to work with me, or if you have any questions.</p>
    <p>Email me at <a href="mailto:cor@pruijs.nl">cor@pruijs.nl</a></p>

</text-page>
</template>

<script>
import TextPage from '@/components/layout/TextPage.vue'

export default {
  name: 'Contact',
  components: { TextPage }
}
</script>

// src/routes/contact.svelte
<section class="text-lg my-8">
  <h2 class="text-3xl font-bold">Contact</h2>
  <p>Feel free to contact me if you would like to work with me, or if you have any questions.</p>
  <p class="mt-4">You can email me at <a class="font-bold underline text-green-500" href="mailto:cor@pruijs.dev">cor@pruijs.dev</a></p>
  <p>GitHub: <a class="font-bold underline text-green-500" href="https://github.com/cor">cor</a></p>
</section>
