// src/views/Contact.vue
<template>
<text-page>
    <h2>Contact</h2>
    <p>Feel free to contact me if you would like to work with me, or if you have any questions.</p>
    <p>Email me at <a href="mailto:cor@pruijs.nl">cor@pruijs.nl</a></p>

</text-page>
</template>

<script>
import TextPage from '@/components/layout/TextPage.vue'

export default {
  name: 'Contact',
  components: { TextPage }
}
</script>

// src/routes/contact/+page.svelte
<svelte:head>
	<title>Cor | Contact</title>
	<meta name="description" content="Cor's contact details" />
</svelte:head>

<div class="text-column">
	<h1>Contact</h1>
	Feel free to contact me for business inquiries or casual chats!

	<h2>Email</h2>
	<a href="mailto:cor@pruijs.dev">cor@pruijs.dev</a>

	<h2>Matrix</h2>
	<a href="">corpruijs:matrix.org</a>

	<h2>GitHub</h2>
	<a href="https://github.com/cor">cor</a>
</div>
